
.artifacts-template: &artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - tor-android-binary/src/main/libs
      - external/include
      - external/lib
      - external/test
    expire_in: 1 week
    when: always

.apt-template: &apt-template |
      export LC_ALL=C.UTF-8
      echo Etc/UTC > /etc/timezone
      echo 'quiet "1";' \
           'APT::Install-Recommends "0";' \
           'APT::Install-Suggests "0";' \
           'APT::Acquire::Retries "20";' \
           'APT::Get::Assume-Yes "true";' \
           'Dpkg::Use-Pty "0";' \
        >> /etc/apt/apt.conf.d/99gitlab
      apt-get update
      apt-get dist-upgrade


.android-template: &android-template
  image: registry.gitlab.com/fdroid/ci-images-client:latest
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - *apt-template

    - apt-get -qy install
        autoconf
        autogen
        automake
        autopoint
        autotools-dev
        gettext-base
        git
        libtool
        make
        patch
        pkg-config
        ca-certificates 
        curl
        gzip
        libtinfo5
        pkg-config
        tar
        unzip
        wget
  script:
  
    - rm -rf $PWD/android-ndk*
    - ndk=android-ndk-`echo $CI_JOB_NAME | awk '{print $2}'`
    - ndkzip=${ndk}-linux-x86_64.zip
    - curl --silent http://dl.google.com/android/repository/${ndkzip} > $ndk_zip
    - echo "57435158f109162f41f2f43d5563d2164e4d5d0364783a9a6fab3ef12cb06ce0  $ndk_zip" > ${ndk_zip}.sha256
    - sha256sum -c ${ndk_zip}.sha256
    - unzip -q $ndk_zip
    - export ANDROID_NDK_HOME=`pwd`/$ndk

    - mkdir -p external
    - export EXTERNAL_ROOT=`pwd`/external
    - cd external

    - mkdir openssl
    - curl --silent --location https://github.com/openssl/openssl/archive/OpenSSL_1_1_1d.tar.gz
        | tar -xz --directory=openssl --strip-components=1
    - cd ..

    - mkdir libevent
    - curl --silent --location https://github.com/libevent/libevent/archive/release-2.1.11-stable.tar.gz
        | tar -xz --directory=libevent --strip-components=1
    - cd ..
    
    - mkdir zstd
    - curl --silent --location https://github.com/facebook/zstd/archive/v1.3.6.tar.gz
        | tar -xz --directory=zstd --strip-components=1
    - cd ..
    
    - git clone https://git.tukaani.org/xz.git
    - cd xz
    - git checkout origin/v2.5
    - cd ..
	
	- git clone --recursive https://git.torproject.org/tor.git
    - git checkout origin/release-0.4.4

android r20 22 default armeabi-v7a:
  <<: *android-template
  script:
    - APP_ABI=armeabi make -C external clean 
    - APP_ABI=armeabi make -C external
  
 

android r20 22 default arm64-v8a:
  <<: *android-template
  script:
    APP_ABI=arm64 NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make -C external clean 
    APP_ABI=arm64 NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make -C external
