
.artifacts-template: &artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - tor-android-binary/src/main/libs
      - external/include
      - external/lib
      - external/test
    expire_in: 1 year
    when: always

.apt-template: &apt-template |
      export LC_ALL=C.UTF-8
      echo Etc/UTC > /etc/timezone
      echo 'quiet "1";' \
           'APT::Install-Recommends "0";' \
           'APT::Install-Suggests "0";' \
           'APT::Acquire::Retries "20";' \
           'APT::Get::Assume-Yes "true";' \
           'Dpkg::Use-Pty "0";' \
        >> /etc/apt/apt.conf.d/99gitlab
      apt-get update
      apt-get dist-upgrade


.android-template: &android-template
  image: ubuntu:latest
  <<: *artifacts-template
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - *apt-template

    - apt-get -qy install
        autoconf
        autogen
        automake
        autopoint
        autotools-dev
        gettext-base
        git
        libtool
        make
        patch
        pkg-config
        ca-certificates 
        curl
        gzip
        libtinfo5
        pkg-config
        tar
        unzip
        wget

    - rm -rf $PWD/android-ndk*
    - ndk=android-ndk-`echo $CI_JOB_NAME | awk '{print $2}'`
    - ndk_zip=${ndk}-linux-x86_64.zip
    - curl --silent http://dl.google.com/android/repository/${ndk_zip} > $ndk_zip
    - echo "c3ebc83c96a4d7f539bd72c241b2be9dcd29bda9  $ndk_zip" > ${ndk_zip}.sha1
    - sha1sum -c ${ndk_zip}.sha1
    - unzip -q $ndk_zip
    - export ANDROID_NDK_HOME=`pwd`/$ndk

    - mkdir -p external
    - export EXTERNAL_ROOT=`pwd`/external
    - cd external

    - git clone --single-branch --branch OpenSSL_1_1_1v https://github.com/openssl/openssl.git

    - git clone --single-branch --branch release-2.1.12-stable https://github.com/libevent/libevent.git

    - git clone --single-branch --branch v1.4.9 https://github.com/facebook/zstd.git

    - git clone --single-branch --branch v5.2.4 https://git.tukaani.org/xz.git

    - git clone --single-branch --branch tor-0.4.8.3-rc https://git.torproject.org/tor.git


android r21e 22 default armeabi-v7a:
  <<: *android-template
  script:
    - APP_ABI=armeabi make clean
    - APP_ABI=armeabi make


android r21e 22 default arm64-v8a:
  <<: *android-template
  script:
    - APP_ABI=arm64 NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make clean
    - APP_ABI=arm64 NDK_PLATFORM_LEVEL=21 NDK_BIT=64 make
